import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import API from "../services/api";
import { CheckCircle2, Users, FileSearch, ClipboardCheck, AlertTriangle, ArrowRight, BarChart3, FileText, PieChart, Calendar, X, Send } from "lucide-react";
import "./FacultyDashboard.css";

export default function FacultyDashboard() {
  const navigate = useNavigate();
  const [data, setData] = useState({
    stats: { totalProjects: 0, pendingReviews: 0, totalStudents: 0, atRiskProjects: 0 },
    projects: [],
    activities: [],
    analytics: null,
    deadlines: [],
    reviewInbox: []
  });
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [modalType, setModalType] = useState("");

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        setLoading(true);
        const [statsRes, activityRes, analyticsRes, deadlinesRes, inboxRes] = await Promise.all([
          API.get("/faculty/dashboard"),
          API.get("/activity/faculty-activity"),
          API.get("/faculty/analytics"),
          API.get("/faculty/deadlines"),
          API.get("/submissions/review-inbox")
        ]);
        
        setData({
          ...statsRes.data,
          activities: activityRes.data,
          analytics: analyticsRes.data,
          deadlines: deadlinesRes.data,
          reviewInbox: Array.isArray(inboxRes.data) ? inboxRes.data : []
        });
      } catch (err) {
        console.error("Dashboard Sync Error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchDashboardData();
  }, []);


  const generateReport = async () => {
    try {
      const { jsPDF } = await import("jspdf");
      const autoTable = (await import("jspdf-autotable")).default;

      const doc = new jsPDF();
      const userName = localStorage.getItem("userName") || "Faculty";

      doc.setFontSize(22);
      doc.setTextColor(37, 99, 235);
      doc.text("ProgressLens Academic Report", 20, 20);

      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by: ${userName}`, 20, 30);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 37);

      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.text("Semester Summary & Dept. Metrics", 20, 50);

      const statsData = [
        ["Total Projects Supervised", data.stats.totalProjects || 0],
        ["Total Students", data.stats.totalStudents || 0],
        ["Average Team Completion", `${data.analytics?.avgCompletion || 0}%`],
        ["High Risk Teams", data.stats.atRiskProjects || 0],
        ["Approved Submissions", data.analytics?.submissionStats?.find(s => s._id === 'Approved')?.count || 0]
      ];

      // jspdf-autotable v5: use autoTable(doc, options) — NOT doc.autoTable()
      autoTable(doc, {
        startY: 55,
        head: [['Academic Metric', 'Current Status']],
        body: statsData,
        theme: 'striped',
        headStyles: { fillColor: [37, 99, 235] }
      });

      const afterTable1Y = doc.lastAutoTable?.finalY ?? 120;

      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42);
      doc.text("Submission Distribution", 20, afterTable1Y + 15);

      const subData = (data.analytics?.submissionStats || []).map(s => [s._id, s.count]);

      autoTable(doc, {
        startY: afterTable1Y + 20,
        head: [['Submission Phase', 'Count']],
        body: subData.length > 0 ? subData : [['No data', '-']],
        theme: 'grid',
        headStyles: { fillColor: [100, 116, 139] }
      });

      doc.save(`ProgressLens_Academic_Report_${new Date().getTime()}.pdf`);

    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Failed to generate PDF report.");
    }
  };


  if (loading) return <div className="loading-screen">⚡ Syncing Academic Progress...</div>;

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { 
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1 }
  };

  return (
    <motion.main 
      className="faculty-dashboard"
      initial="hidden"
      animate="visible"
      variants={containerVariants}
    >
      <header className="page-header">
        <div>
          <h1 className="page-title">Faculty Dashboard</h1>
          <p className="text-secondary">Monitor and review student projects</p>
        </div>
        <span className="role-badge">Faculty Access</span>
      </header>

      {/* STATS STRIP */}
      <section className="stats-grid">
        <motion.div className="stat-card blue" variants={itemVariants}>
          <div className="stat-icon"><FileSearch size={20} /></div>
          <p>Total Projects</p>
          <h2>{data.stats.totalProjects || 0}</h2>
        </motion.div>
        <motion.div className="stat-card orange" variants={itemVariants}>
          <div className="stat-icon"><ClipboardCheck size={20} /></div>
          <p>Pending Reviews</p>
          <h2>{data.stats.pendingReviews || 0}</h2>
        </motion.div>
        <motion.div className="stat-card green" variants={itemVariants}>
          <div className="stat-icon"><Users size={20} /></div>
          <p>Total Students</p>
          <h2>{data.stats.totalStudents || 0}</h2>
        </motion.div>
        <motion.div className="stat-card red" variants={itemVariants}>
          <div className="stat-icon"><AlertTriangle size={20} /></div>
          <p>At Risk Projects</p>
          <h2>{data.stats.atRiskProjects || 0}</h2>
        </motion.div>
      </section>

      {/* ANNOUNCEMENTS SECTION */}
      <motion.div className="announcement-post-card card" variants={itemVariants} style={{ marginBottom: 32 }}>
        <div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <h3>Broadcast Announcements</h3>
            <p className="text-secondary small">Reach all project teams instantly</p>
          </div>
          <Send size={20} color="var(--accent-primary)" />
        </div>
        
        <div className="form-content" style={{ marginTop: 24 }}>
          <div className="form-row" style={{ display: 'flex', gap: 16, marginBottom: 16 }}>
            <input 
              id="ann-title"
              placeholder="Announcement Title" 
              style={{ flex: 2, padding: '12px', border: '1px solid var(--border-color)', borderRadius: '8px' }}
            />
            <select 
              id="ann-type"
              style={{ flex: 1, padding: '12px', border: '1px solid var(--border-color)', borderRadius: '8px' }}
            >
              <option value="General">General Update</option>
              <option value="Deadline">Deadline Reminder</option>
            </select>
          </div>
          <textarea 
            id="ann-content"
            placeholder="Enter your message to students..." 
            style={{ width: '100%', padding: '12px', border: '1px solid var(--border-color)', borderRadius: '8px', minHeight: 100, marginBottom: 16 }}
          />
          <button 
            className="btn btn-primary"
            style={{ width: '100%', padding: '14px', background: 'var(--accent-primary)', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 700, cursor: 'pointer' }}
            onClick={async () => {
              const title = document.getElementById("ann-title").value;
              const content = document.getElementById("ann-content").value;
              const type = document.getElementById("ann-type").value;
              if(!title || !content) return alert("Please fill all fields");
              
              try {
                await API.post("/faculty/announcements", { title, content, type });
                alert("Announcement Broadcasted!");
                document.getElementById("ann-title").value = "";
                document.getElementById("ann-content").value = "";
              } catch (err) {
                alert("Failed to broadcast.");
              }
            }}
          >
            Send Broadcast
          </button>
        </div>
      </motion.div>

      <div className="dashboard-content-grid">
        <motion.div className="panel card" variants={itemVariants}>
          <div className="panel-header">
            <h3>Review Center</h3>
            {data.stats.pendingReviews > 0 && (
              <span className="review-count-badge">{data.stats.pendingReviews} pending</span>
            )}
          </div>

          {data.reviewInbox.length === 0 ? (
            <div className="alert-message success">
              <CheckCircle2 size={18} />
              <span>All caught up! No pending reviews. ✅</span>
            </div>
          ) : (
            <div className="review-inbox-preview">
              {data.reviewInbox.slice(0, 3).map((item) => (
                <div
                  key={item._id}
                  className="review-inbox-item"
                  onClick={() => navigate(`/faculty/projects/${item.project?._id}`)}
                >
                  <div className="review-inbox-info">
                    <strong>{item.project?.title || "Unknown Project"}</strong>
                    <span>{item.phase} Phase · {item.submittedBy?.name}</span>
                  </div>
                  <span className={`status-dot ${item.status === 'Pending' ? 'dot-pending' : 'dot-revision'}`}></span>
                </div>
              ))}
              {data.reviewInbox.length > 3 && (
                <p className="review-more-text">+{data.reviewInbox.length - 3} more awaiting review</p>
              )}
            </div>
          )}

          <button className="btn btn-primary w-full" style={{ marginTop: 16 }} onClick={() => navigate("/faculty/reviews")}>
            Open Review Center <ArrowRight size={18} />
          </button>
        </motion.div>

        <motion.div className="panel card" variants={itemVariants}>
          <div className="panel-header">
            <h3>Recent Activity</h3>
          </div>
          <div className="activity-list">
            {data.activities && data.activities.length > 0 ? (
              data.activities.slice(0, 5).map((act, index) => {
                const isFaculty = act.user?.role === "faculty";
                return (
                  <div key={index} className="activity-item">
                    <div className={`activity-dot ${isFaculty ? 'blue' : 'green'}`}></div>
                    <div className="activity-info">
                      <p className="activity-msg">
                        <span className="user-name">{isFaculty ? "You " : (act.user?.name || "Student ")}</span>
                        {act.message || "updated the project"}
                      </p>
                      <span className="activity-time">
                        {new Date(act.timestamp || act.createdAt).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                );
              })
            ) : (
              <p className="empty-text">No recent activity recorded.</p>
            )}
          </div>
        </motion.div>
      </div>

      {/* DATA & ANALYTICS SECTION */}
      <motion.section className="analytics-section" variants={itemVariants}>
        <div className="section-header">
          <h3 className="text-muted text-uppercase small font-bold">Data & Analytics</h3>
        </div>
        <div className="analytics-grid">
          <div className="analytics-card card clickable" onClick={() => { setModalType("charts"); setShowModal(true); }}>
            <div className="analytics-icon blue"><BarChart3 size={20} /></div>
            <div className="analytics-info">
              <h4>Charts</h4>
              <p className="font-bold">Progress charts</p>
              <p className="text-secondary small">Line/bar charts of task completion over time</p>
            </div>
          </div>

          <div className="analytics-card card clickable" onClick={generateReport}>
            <div className="analytics-icon orange"><FileText size={20} /></div>
            <div className="analytics-info">
              <h4>Export</h4>
              <p className="font-bold">PDF reports</p>
              <p className="text-secondary small">One-click semester summary for faculty</p>
            </div>
          </div>

          <div className="analytics-card card clickable" onClick={() => { setModalType("analytics"); setShowModal(true); }}>
            <div className="analytics-icon green"><PieChart size={20} /></div>
            <div className="analytics-info">
              <h4>Analytics</h4>
              <p className="font-bold">Dept. overview</p>
              <p className="text-secondary small">Aggregated stats across all teams / batches</p>
            </div>
          </div>

          <div className="analytics-card card clickable" onClick={() => { setModalType("planning"); setShowModal(true); }}>
            <div className="analytics-icon purple"><Calendar size={20} /></div>
            <div className="analytics-info">
              <h4>Planning</h4>
              <p className="font-bold">Calendar view</p>
              <p className="text-secondary small">Monthly calendar with colour-coded deadlines</p>
            </div>
          </div>
        </div>
      </motion.section>

      {/* ANALYTICS MODAL */}
      <AnimatePresence>
        {showModal && (
          <motion.div 
            className="modal-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setShowModal(false)}
          >
            <motion.div 
              className="modal-content"
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="modal-header">
                <h3>{modalType === "charts" ? "Progress Analytics" : modalType === "analytics" ? "Departmental Overview" : "Planning Calendar"}</h3>
                <button className="close-btn" onClick={() => setShowModal(false)}><X size={20} /></button>
              </div>
              
              <div className="modal-body">
                {modalType === "charts" && (
                  <div className="chart-container" style={{ height: 300 }}>
                    <p className="text-secondary small mb-4">Task completion rate over the last 6 months</p>
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={data.analytics?.completionTrend || []}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                        <XAxis dataKey="name" axisLine={false} tickLine={false} />
                        <YAxis axisLine={false} tickLine={false} />
                        <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)' }} />
                        <Bar dataKey="tasks" fill="var(--accent-primary)" radius={[4, 4, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                )}

                {modalType === "analytics" && (
                  <div className="dept-stats">
                    <div className="stat-row">
                      <span>Avg. Project Completion</span>
                      <span className="status-pill status-success">{data.analytics?.avgCompletion || 0}%</span>
                    </div>
                    <div className="stat-row">
                      <span>Projects On Track</span>
                      <span className="font-bold">{data.analytics?.healthStats?.good || 0}</span>
                    </div>
                    <div className="stat-row">
                      <span>Projects At Risk</span>
                      <span className="font-bold text-danger">{data.analytics?.healthStats?.danger || 0}</span>
                    </div>
                  </div>
                )}

                {modalType === "planning" && (
                  <div className="planning-view">
                    <p className="text-secondary small mb-3">Manage Upcoming Deadlines & Milestones</p>
                    
                    <div className="deadline-form" style={{display: 'flex', gap: '10px', marginBottom: '20px'}}>
                      <input type="text" id="new-dl-title" placeholder="Deadline Title" className="form-input" style={{flex: 2, padding: '8px', borderRadius: '8px', border: '1px solid #ccc'}} />
                      <input type="date" id="new-dl-date" className="form-input" style={{flex: 1, padding: '8px', borderRadius: '8px', border: '1px solid #ccc'}} />
                      <button 
                        className="btn btn-primary" 
                        style={{padding: '8px 16px', borderRadius: '8px', border: 'none', background: 'var(--accent-primary)', color: 'white', cursor: 'pointer'}}
                        onClick={async () => {
                          const title = document.getElementById("new-dl-title").value;
                          const date = document.getElementById("new-dl-date").value;
                          if (!title || !date) return alert("Please fill both title and date.");
                          try {
                            const res = await API.post("/faculty/deadlines", { title, date, type: "General" });
                            setData(prev => ({ ...prev, deadlines: [...prev.deadlines, res.data].sort((a,b) => new Date(a.date) - new Date(b.date)) }));
                            document.getElementById("new-dl-title").value = "";
                            document.getElementById("new-dl-date").value = "";
                          } catch (err) {
                            alert("Failed to create deadline.");
                          }
                        }}
                      >
                        Add
                      </button>
                    </div>

                    <div className="upcoming-events" style={{maxHeight: '250px', overflowY: 'auto'}}>
                      {data.deadlines && data.deadlines.length > 0 ? data.deadlines.map(dl => (
                        <div className="event-item" key={dl._id} style={{display: 'flex', justifyContent: 'space-between', padding: '12px', background: '#f8fafc', borderRadius: '8px', marginBottom: '8px'}}>
                          <span className="event-date" style={{fontWeight: 'bold', color: 'var(--accent-primary)'}}>
                            {new Date(dl.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                          </span>
                          <span className="event-name">{dl.title}</span>
                        </div>
                      )) : (
                        <p className="text-secondary text-center">No upcoming deadlines.</p>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.main>
  );
}